# fly.toml app configuration file generated for mookbark on 2023-11-11T18:55:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mookbark"
primary_region = "cdg"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
interval = "30s"
timeout = "5s"
grace_period = "10s"
method = "GET"
path = "/health-check"
