//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::bookmark::Entity as Bookmark;
pub use super::closure::Entity as Closure;
pub use super::container::Entity as Container;
pub use super::user::Entity as User;
